### ISSUE TITLE
Patch not working after game update

### ISSUE THREAD

**Issue by Chachardus** [Lyall/TormentedSoulsFix#1]
Game has been updated yesterday on Steam. This broke the ultrawide patch.

**Comment by Lyall** [comment]
Looks like they switched from using Mono to IL2CPP. Along with that, another user ([p1xel8ted](https://github.com/p1xel8ted)) has been developing a much improved fix [over here](https://github.com/p1xel8ted/UltrawideFixes/releases/tag/TormentedSouls) which I recommend using.

This repository will be archived and a notice will be put up directing others to p1xel8ted's fix.
